intg=int(input())
inta=int(input())
enc=int(input())
ind=int(input())
stru=int(input())
if (intg==1 or inta==1) and enc==1 and ind==1 and stru==1:
    print("Trabalho aborda Interface Grafica? (0 - Nao 1 - Sim)")
    print("Trabalho aborda Inteligencia Artificial? (0 - Nao 1 - Sim)")
    print("Trabalho aborda Encapsulamento? (0 - Nao 1 - Sim)")
    print("Trabalho aborda Indentacao? (0 - Nao 1 - Sim)")
    print("Trabalho aborda Structs? (0 - Nao 1 - Sim)")
    print("Seu trabalho sera avaliado.")
else:
 print("Trabalho aborda Interface Grafica? (0 - Nao 1 - Sim)")
 print("Trabalho aborda Inteligencia Artificial? (0 - Nao 1 - Sim)")
 print("Trabalho aborda Encapsulamento? (0 - Nao 1 - Sim)")
 print("Trabalho aborda Indentacao? (0 - Nao 1 - Sim)")
 print("Trabalho aborda Structs? (0 - Nao 1 - Sim)")
 print("Seu trabalho nao sera avaliado, nota 0.")